"""内置默认术语表 (~200 条 AI/技术领域术语)。

每条: {"en": str, "zh": str, "domain": str}
"""
import logging

logger = logging.getLogger(__name__)

DEFAULT_GLOSSARY: list[dict[str, str]] = [
    # === AI / Machine Learning ===
    {"en": "transformer", "zh": "Transformer 模型", "domain": "AI"},
    {"en": "attention mechanism", "zh": "注意力机制", "domain": "AI"},
    {"en": "self-attention", "zh": "自注意力", "domain": "AI"},
    {"en": "multi-head attention", "zh": "多头注意力", "domain": "AI"},
    {"en": "cross-attention", "zh": "交叉注意力", "domain": "AI"},
    {"en": "positional encoding", "zh": "位置编码", "domain": "AI"},
    {"en": "layer normalization", "zh": "层归一化", "domain": "AI"},
    {"en": "batch normalization", "zh": "批归一化", "domain": "AI"},
    {"en": "dropout", "zh": "随机失活", "domain": "AI"},
    {"en": "residual connection", "zh": "残差连接", "domain": "AI"},
    {"en": "feed-forward network", "zh": "前馈网络", "domain": "AI"},
    {"en": "activation function", "zh": "激活函数", "domain": "AI"},
    {"en": "softmax", "zh": "Softmax 归一化", "domain": "AI"},
    {"en": "embedding", "zh": "嵌入向量", "domain": "AI"},
    {"en": "tokenization", "zh": "分词", "domain": "AI"},
    {"en": "tokenizer", "zh": "分词器", "domain": "AI"},
    {"en": "vocabulary", "zh": "词表", "domain": "AI"},
    {"en": "pre-training", "zh": "预训练", "domain": "AI"},
    {"en": "fine-tuning", "zh": "微调", "domain": "AI"},
    {"en": "instruction tuning", "zh": "指令微调", "domain": "AI"},
    {"en": "alignment", "zh": "对齐", "domain": "AI"},
    {"en": "reinforcement learning from human feedback", "zh": "基于人类反馈的强化学习", "domain": "AI"},
    {"en": "reward model", "zh": "奖励模型", "domain": "AI"},
    {"en": "policy gradient", "zh": "策略梯度", "domain": "AI"},
    {"en": "loss function", "zh": "损失函数", "domain": "AI"},
    {"en": "cross-entropy loss", "zh": "交叉熵损失", "domain": "AI"},
    {"en": "gradient descent", "zh": "梯度下降", "domain": "AI"},
    {"en": "backpropagation", "zh": "反向传播", "domain": "AI"},
    {"en": "learning rate", "zh": "学习率", "domain": "AI"},
    {"en": "weight decay", "zh": "权重衰减", "domain": "AI"},
    {"en": "overfitting", "zh": "过拟合", "domain": "AI"},
    {"en": "underfitting", "zh": "欠拟合", "domain": "AI"},
    {"en": "generalization", "zh": "泛化能力", "domain": "AI"},
    {"en": "inference", "zh": "推理", "domain": "AI"},
    {"en": "latency", "zh": "延迟", "domain": "AI"},
    {"en": "throughput", "zh": "吞吐量", "domain": "AI"},
    {"en": "hallucination", "zh": "幻觉", "domain": "AI"},
    {"en": "prompt engineering", "zh": "提示工程", "domain": "AI"},
    {"en": "few-shot learning", "zh": "少样本学习", "domain": "AI"},
    {"en": "zero-shot learning", "zh": "零样本学习", "domain": "AI"},
    {"en": "chain of thought", "zh": "思维链", "domain": "AI"},
    {"en": "retrieval-augmented generation", "zh": "检索增强生成", "domain": "AI"},
    {"en": "vector database", "zh": "向量数据库", "domain": "AI"},
    {"en": "semantic search", "zh": "语义搜索", "domain": "AI"},
    {"en": "knowledge graph", "zh": "知识图谱", "domain": "AI"},
    {"en": "neural network", "zh": "神经网络", "domain": "AI"},
    {"en": "deep learning", "zh": "深度学习", "domain": "AI"},
    {"en": "machine learning", "zh": "机器学习", "domain": "AI"},
    {"en": "supervised learning", "zh": "监督学习", "domain": "AI"},
    {"en": "unsupervised learning", "zh": "无监督学习", "domain": "AI"},
    {"en": "semi-supervised learning", "zh": "半监督学习", "domain": "AI"},
    {"en": "transfer learning", "zh": "迁移学习", "domain": "AI"},
    {"en": "curriculum learning", "zh": "课程学习", "domain": "AI"},
    {"en": "contrastive learning", "zh": "对比学习", "domain": "AI"},
    {"en": "diffusion model", "zh": "扩散模型", "domain": "AI"},
    {"en": "latent space", "zh": "隐空间", "domain": "AI"},
    {"en": "encoder", "zh": "编码器", "domain": "AI"},
    {"en": "decoder", "zh": "解码器", "domain": "AI"},
    {"en": "encoder-decoder", "zh": "编码器-解码器架构", "domain": "AI"},
    {"en": "autoregressive", "zh": "自回归的", "domain": "AI"},
    {"en": "next token prediction", "zh": "下一个词元预测", "domain": "AI"},
    {"en": "masked language modeling", "zh": "掩码语言建模", "domain": "AI"},
    {"en": "causal language modeling", "zh": "因果语言建模", "domain": "AI"},
    {"en": "beam search", "zh": "束搜索", "domain": "AI"},
    {"en": "top-k sampling", "zh": "Top-K 采样", "domain": "AI"},
    {"en": "top-p sampling", "zh": "核采样", "domain": "AI"},
    {"en": "temperature", "zh": "温度参数", "domain": "AI"},
    {"en": "quantization", "zh": "量化", "domain": "AI"},
    {"en": "pruning", "zh": "剪枝", "domain": "AI"},
    {"en": "knowledge distillation", "zh": "知识蒸馏", "domain": "AI"},
    {"en": "mixture of experts", "zh": "混合专家", "domain": "AI"},
    {"en": "low-rank adaptation", "zh": "低秩适配", "domain": "AI"},
    {"en": "parameter-efficient fine-tuning", "zh": "参数高效微调", "domain": "AI"},
    {"en": "foundation model", "zh": "基础模型", "domain": "AI"},
    {"en": "large language model", "zh": "大语言模型", "domain": "AI"},
    {"en": "multimodal model", "zh": "多模态模型", "domain": "AI"},
    {"en": "vision language model", "zh": "视觉语言模型", "domain": "AI"},
    {"en": "speech recognition", "zh": "语音识别", "domain": "AI"},
    {"en": "text-to-speech", "zh": "语音合成", "domain": "AI"},
    {"en": "machine translation", "zh": "机器翻译", "domain": "AI"},
    {"en": "simultaneous interpretation", "zh": "同声传译", "domain": "AI"},
    {"en": "named entity recognition", "zh": "命名实体识别", "domain": "AI"},
    {"en": "sentiment analysis", "zh": "情感分析", "domain": "AI"},
    {"en": "text summarization", "zh": "文本摘要", "domain": "AI"},
    {"en": "question answering", "zh": "问答系统", "domain": "AI"},
    {"en": "anomaly detection", "zh": "异常检测", "domain": "AI"},
    {"en": "recommendation system", "zh": "推荐系统", "domain": "AI"},
    {"en": "collaborative filtering", "zh": "协同过滤", "domain": "AI"},
    {"en": "feature engineering", "zh": "特征工程", "domain": "AI"},
    {"en": "feature extraction", "zh": "特征提取", "domain": "AI"},
    {"en": "dimensionality reduction", "zh": "降维", "domain": "AI"},
    {"en": "principal component analysis", "zh": "主成分分析", "domain": "AI"},
    {"en": "clustering", "zh": "聚类", "domain": "AI"},
    {"en": "classification", "zh": "分类", "domain": "AI"},
    {"en": "regression", "zh": "回归", "domain": "AI"},
    {"en": "decision tree", "zh": "决策树", "domain": "AI"},
    {"en": "random forest", "zh": "随机森林", "domain": "AI"},
    {"en": "support vector machine", "zh": "支持向量机", "domain": "AI"},
    {"en": "gradient boosting", "zh": "梯度提升", "domain": "AI"},
    {"en": "hyperparameter", "zh": "超参数", "domain": "AI"},
    {"en": "epoch", "zh": "训练轮次", "domain": "AI"},
    {"en": "batch size", "zh": "批次大小", "domain": "AI"},
    {"en": "checkpoint", "zh": "检查点", "domain": "AI"},
    {"en": "benchmark", "zh": "基准测试", "domain": "AI"},
    {"en": "state-of-the-art", "zh": "最先进的", "domain": "AI"},
    {"en": "ablation study", "zh": "消融实验", "domain": "AI"},
    {"en": "federated learning", "zh": "联邦学习", "domain": "AI"},
    {"en": "synthetic data", "zh": "合成数据", "domain": "AI"},
    {"en": "data augmentation", "zh": "数据增强", "domain": "AI"},
    {"en": "active learning", "zh": "主动学习", "domain": "AI"},
    {"en": "model distillation", "zh": "模型蒸馏", "domain": "AI"},
    {"en": "speculative decoding", "zh": "推测解码", "domain": "AI"},
    {"en": "token", "zh": "词元/令牌", "domain": "AI"},
    {"en": "context window", "zh": "上下文窗口", "domain": "AI"},
    {"en": "language model", "zh": "语言模型", "domain": "AI"},
    {"en": "code generation", "zh": "代码生成", "domain": "AI"},
    {"en": "code completion", "zh": "代码补全", "domain": "AI"},

    # === Computer Science / Programming ===
    {"en": "open source", "zh": "开源的", "domain": "CS"},
    {"en": "repository", "zh": "代码仓库", "domain": "CS"},
    {"en": "pull request", "zh": "拉取请求", "domain": "CS"},
    {"en": "code review", "zh": "代码评审", "domain": "CS"},
    {"en": "merge conflict", "zh": "合并冲突", "domain": "CS"},
    {"en": "continuous integration", "zh": "持续集成", "domain": "CS"},
    {"en": "continuous deployment", "zh": "持续部署", "domain": "CS"},
    {"en": "unit test", "zh": "单元测试", "domain": "CS"},
    {"en": "integration test", "zh": "集成测试", "domain": "CS"},
    {"en": "end-to-end test", "zh": "端到端测试", "domain": "CS"},
    {"en": "regression test", "zh": "回归测试", "domain": "CS"},
    {"en": "microservice", "zh": "微服务", "domain": "CS"},
    {"en": "monolith", "zh": "单体架构", "domain": "CS"},
    {"en": "load balancer", "zh": "负载均衡器", "domain": "CS"},
    {"en": "reverse proxy", "zh": "反向代理", "domain": "CS"},
    {"en": "message queue", "zh": "消息队列", "domain": "CS"},
    {"en": "pub/sub", "zh": "发布/订阅模式", "domain": "CS"},
    {"en": "event sourcing", "zh": "事件溯源", "domain": "CS"},
    {"en": "idempotency", "zh": "幂等性", "domain": "CS"},
    {"en": "horizontal scaling", "zh": "水平扩展", "domain": "CS"},
    {"en": "vertical scaling", "zh": "垂直扩展", "domain": "CS"},
    {"en": "sharding", "zh": "分片", "domain": "CS"},
    {"en": "replication", "zh": "复制", "domain": "CS"},
    {"en": "caching", "zh": "缓存", "domain": "CS"},
    {"en": "redis", "zh": "Redis 缓存", "domain": "CS"},
    {"en": "postgresql", "zh": "PostgreSQL 数据库", "domain": "CS"},
    {"en": "mongodb", "zh": "MongoDB 数据库", "domain": "CS"},
    {"en": "graphql", "zh": "GraphQL 查询语言", "domain": "CS"},
    {"en": "restful api", "zh": "RESTful API", "domain": "CS"},
    {"en": "websocket", "zh": "WebSocket 协议", "domain": "CS"},
    {"en": "lambda function", "zh": "Lambda 函数", "domain": "CS"},
    {"en": "serverless", "zh": "无服务器架构", "domain": "CS"},
    {"en": "containerization", "zh": "容器化", "domain": "CS"},
    {"en": "orchestration", "zh": "编排", "domain": "CS"},
    {"en": "infrastructure as code", "zh": "基础设施即代码", "domain": "CS"},
    {"en": "terraform", "zh": "Terraform 基础设施工具", "domain": "CS"},
    {"en": "observability", "zh": "可观测性", "domain": "CS"},
    {"en": "monitoring", "zh": "监控", "domain": "CS"},
    {"en": "alerting", "zh": "告警", "domain": "CS"},
    {"en": "logging", "zh": "日志记录", "domain": "CS"},
    {"en": "tracing", "zh": "链路追踪", "domain": "CS"},
    {"en": "dashboard", "zh": "仪表盘", "domain": "CS"},
    {"en": "git", "zh": "Git 版本控制", "domain": "CS"},
    {"en": "linux", "zh": "Linux 操作系统", "domain": "CS"},
    {"en": "compiler", "zh": "编译器", "domain": "CS"},
    {"en": "interpreter", "zh": "解释器", "domain": "CS"},
    {"en": "runtime", "zh": "运行时", "domain": "CS"},
    {"en": "garbage collector", "zh": "垃圾回收器", "domain": "CS"},
    {"en": "type system", "zh": "类型系统", "domain": "CS"},
    {"en": "strongly typed", "zh": "强类型的", "domain": "CS"},
    {"en": "dynamically typed", "zh": "动态类型的", "domain": "CS"},
    {"en": "polymorphism", "zh": "多态", "domain": "CS"},
    {"en": "inheritance", "zh": "继承", "domain": "CS"},
    {"en": "composition", "zh": "组合", "domain": "CS"},
    {"en": "static analysis", "zh": "静态分析", "domain": "CS"},
    {"en": "dynamic analysis", "zh": "动态分析", "domain": "CS"},
    {"en": "memory leak", "zh": "内存泄漏", "domain": "CS"},
    {"en": "race condition", "zh": "竞态条件", "domain": "CS"},
    {"en": "deadlock", "zh": "死锁", "domain": "CS"},
    {"en": "tail latency", "zh": "尾部延迟", "domain": "CS"},
    {"en": "blue-green deployment", "zh": "蓝绿部署", "domain": "CS"},
    {"en": "canary release", "zh": "金丝雀发布", "domain": "CS"},
    {"en": "feature flag", "zh": "功能开关", "domain": "CS"},
    {"en": "A/B testing", "zh": "A/B 测试", "domain": "CS"},
    {"en": "edge computing", "zh": "边缘计算", "domain": "CS"},

    # === Business / Product ===
    {"en": "agile", "zh": "敏捷开发", "domain": "Business"},
    {"en": "scrum", "zh": "Scrum 敏捷框架", "domain": "Business"},
    {"en": "sprint", "zh": "冲刺迭代", "domain": "Business"},
    {"en": "kanban", "zh": "看板方法", "domain": "Business"},
    {"en": "minimum viable product", "zh": "最小可行产品", "domain": "Business"},
    {"en": "proof of concept", "zh": "概念验证", "domain": "Business"},
    {"en": "product-market fit", "zh": "产品-市场匹配", "domain": "Business"},
    {"en": "go-to-market", "zh": "上市策略", "domain": "Business"},
    {"en": "key performance indicator", "zh": "关键绩效指标", "domain": "Business"},
    {"en": "return on investment", "zh": "投资回报率", "domain": "Business"},
    {"en": "total addressable market", "zh": "总可寻址市场", "domain": "Business"},
    {"en": "customer acquisition cost", "zh": "客户获取成本", "domain": "Business"},
    {"en": "lifetime value", "zh": "客户终身价值", "domain": "Business"},
    {"en": "churn rate", "zh": "流失率", "domain": "Business"},
    {"en": "retention", "zh": "用户留存", "domain": "Business"},
    {"en": "conversion rate", "zh": "转化率", "domain": "Business"},
    {"en": "funnel", "zh": "转化漏斗", "domain": "Business"},
    {"en": "onboarding", "zh": "用户引导", "domain": "Business"},
    {"en": "stakeholder", "zh": "利益相关方", "domain": "Business"},
    {"en": "deliverable", "zh": "交付物", "domain": "Business"},
    {"en": "milestone", "zh": "里程碑", "domain": "Business"},
    {"en": "bandwidth", "zh": "人力带宽", "domain": "Business"},
    {"en": "scalability", "zh": "可扩展性", "domain": "Business"},
    {"en": "monetization", "zh": "变现", "domain": "Business"},
    {"en": "freemium", "zh": "免费增值模式", "domain": "Business"},
    {"en": "subscription", "zh": "订阅制", "domain": "Business"},
    {"en": "enterprise", "zh": "企业级", "domain": "Business"},
    {"en": "B2B", "zh": "企业对企业", "domain": "Business"},
    {"en": "B2C", "zh": "企业对消费者", "domain": "Business"},
    {"en": "vertical SaaS", "zh": "垂直领域 SaaS", "domain": "Business"},
    {"en": "horizontal SaaS", "zh": "通用型 SaaS", "domain": "Business"},
    {"en": "API-first", "zh": "API 优先的", "domain": "Business"},
    {"en": "mobile-first", "zh": "移动优先的", "domain": "Business"},
    {"en": "cloud-native", "zh": "云原生的", "domain": "Business"},
]
